ignore_build_only_deps:
- numpy
- python
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
extend_keys:
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
- extend_keys
lzo:
- '2'
giflib:
- '5'
dbus:
- '1'
channel_targets:
- defaults
libgsasl:
- '1.8'
openssl:
- 1.1.1
libxml2:
- '2.9'
vc:
- '14'
g2clib:
- '1.6'
libtiff:
- '4.1'
serf:
- 1.3.9
cxx_compiler:
- vs2017
jpeg:
- '9'
tk:
- '8.6'
libdap4:
- '3.19'
libpng:
- '1.6'
fortran_compiler_version:
- 2019.0.0
fortran_compiler:
- intel-fortran
zlib:
- '1.2'
glib:
- '2'
clang_variant:
- clang
libkml:
- '1.3'
libnetcdf:
- '4.8'
cairo:
- '1.14'
m2w64_c_compiler:
- m2w64-toolchain
apr:
- 1.6.3
rust_compiler_version:
- 1.56.0
r_version:
- 3.5.0
geos:
- 3.8.0
proj:
- 6.2.1
VERBOSE_CM:
- VERBOSE=1
icu:
- '58'
boost_cpp:
- '1.73'
libffi:
- '3.4'
cyrus_sasl:
- 2.1.26
mkl:
- '2021'
llvm_variant:
- llvm
hdfeos5:
- '5.1'
VERBOSE_AT:
- V=1
gstreamer:
- '1.14'
blas_impl:
- mkl
proj4:
- 5.2.0
fontconfig:
- '2.13'
hdf4:
- '4.2'
libprotobuf:
- 3.11.2
openblas:
- 0.3.3
rust_compiler:
- rust
- rust-gnu
mpfr:
- '4'
libgd:
- 2.2.5
python_impl:
- cpython
cross_compiler_target_platform:
- win-32
- win-64
bzip2:
- '1.0'
pixman:
- '0.30'
libxslt:
- '1.1'
python_implementation:
- cpython
qtwebkit:
- 'true'
libgdal:
- '3.0'
gst_plugins_base:
- '1.14'
sqlite:
- '3'
gmp:
- '6.1'
boost:
- '1.73'
r_base:
- '3.5'
freetype:
- '2.10'
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
c_compiler:
- vs2017
libwebp:
- 1.2.0
expat:
- '2.2'
cpu_optimization_target:
- nocona
perl:
- '5.26'
lua:
- '5'
target_platform:
- win-64
harfbuzz:
- '2.4'
openjpeg:
- '2.3'
m2w64_cxx_compiler:
- m2w64-toolchain
gnu:
- 2.12.2
hdfeos2:
- '2.20'
m2w64_fortran_compiler:
- m2w64-toolchain
xz:
- '5'
r_implementation:
- mro-base
- r-base
hdf5:
- 1.10.6
readline:
- '8.0'
numpy:
- '1.16'
python:
- '3.9'
zip_keys:
- - python
  - numpy
