# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# C:\Users\builder\adipietro\aggregate\cffi-feedstock\recipe, last modified Thu Jan 20 06:40:45 2022
# ------------------------------------------------

package:
  name: cffi
  version: 1.15.0
source:
  patches:
    - 0001-Link-to-dl-library.patch
  sha256: 920f0d66a896c2d99f0adbb391f990a84091179542c205fa53ce5787aff87954
  url: https://pypi.io/packages/source/c/cffi/cffi-1.15.0.tar.gz
build:
  missing_dso_whitelist: null
  number: '1'
  script: c:\\ci_310\\cffi_1642682485096\\_h_env\\python.exe -m pip install . --no-deps
    -vv
  string: py39h2bbff1b_1
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2021.10.26 haa95532_2
    - certifi 2021.10.8 py39haa95532_2
    - openssl 1.1.1m h2bbff1b_0
    - pip 21.2.4 py39haa95532_0
    - python 3.9.7 h6244533_1
    - setuptools 58.0.4 py39haa95532_0
    - sqlite 3.37.0 h2bbff1b_0
    - tzdata 2021e hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - pycparser
    - python >=3.9,<3.10.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - _cffi_backend
    - cffi
  requires:
    - pip
about:
  description: 'Cffi aims to allow users to call C code from Python without having
    to

    learn a 3rd language. It provides a convenient and reliable way to call

    compiled C code from Python using interface declarations written in C.

    '
  dev_url: https://foss.heptapod.net/pypy/cffi
  doc_source_url: https://foss.heptapod.net/pypy/cffi/-/tree/branch/default/doc/source
  doc_url: https://cffi.readthedocs.io/en/latest/
  home: http://cffi.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - goanpeca
    - inducer
    - mingwandroid
    - ocefpaf
