# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\Users\builder\adipietro\aggregate\pywin32-feedstock\recipe, last modified Fri Apr 15 14:29:45 2022
# ------------------------------------------------

package:
  name: pywin32
  version: '302'
source:
  patches:
    - 0003-remove-PATH-pth-hack.patch
    - disable_exchange_modules.patch
  sha256: 47fd53c0561ff3019043e86880597aacbd736910d8add485117d8ad055441927
  url: https://github.com/mhammond/pywin32/archive/b302.tar.gz
build:
  number: '2'
  string: py39h2bbff1b_2
requirements:
  build:
    - m2-gcc-libs 5.3.0 4
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2022.3.29 haa95532_0
    - certifi 2021.10.8 py39haa95532_2
    - openssl 1.1.1n h2bbff1b_0
    - pip 21.2.4 py39haa95532_0
    - python 3.9.12 h6244533_0
    - setuptools 61.2.0 py39haa95532_0
    - sqlite 3.38.2 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - python >=3.9,<3.10.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
about:
  description: 'A set of extension modules that provides access to many of the Windows
    API functions.

    '
  dev_url: https://github.com/mhammond/pywin32
  doc_url: https://mhammond.github.io/pywin32
  home: https://github.com/mhammond/pywin32
  license: HPND AND BSD-3-Clause AND LGPL-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - mingwandroid
    - nicoddemus
