# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# C:\ci\containers\00001po4m93\tmp\build\80754af9\rsync-recipes\conda-package-handling-1.8.1-python_3.9-on-winbuilder, last modified Mon Apr  4 15:51:01 2022
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 1.8.1
source:
  sha256: 22d89206f55616b774a775038a6777b0d2e9b8706c23068c4d3091f114c8a4e8
  url: https://github.com/conda/conda-package-handling/archive/1.8.1.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  missing_dso_whitelist:
    - '*/VCRUNTIME140.dll'
    - MSVCR90.dll
  number: '0'
  script: C:\\ci\\conda-package-handling_1649106011304\\_h_env\\python.exe -m pip
    install . --no-deps -vv
  string: py39h8cc25b3_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - _libarchive_static_for_cph 3.4.3 h62dcd97_2
    - ca-certificates 2022.3.29 haa95532_0
    - certifi 2021.10.8 py39haa95532_2
    - cython 0.29.28 py39hd77b12b_0
    - openssl 1.1.1n h2bbff1b_0
    - pip 21.2.4 py39haa95532_0
    - python 3.9.11 h6244533_2
    - setuptools 58.0.4 py39haa95532_0
    - sqlite 3.38.2 h2bbff1b_0
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py39haa95532_2
  run:
    - python >=3.9,<3.10.0a0
    - tqdm
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pytest tests -k "not test_secure_refusal_to_extract_abs_paths"
  imports:
    - conda_package_handling
    - conda_package_handling.archive_utils_cy
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
  source_files:
    - tests
about:
  dev_url: https://github.com/conda/conda-package-handling
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - static_deps_licenses/bzip2.txt
    - static_deps_licenses/libarchive.txt
    - static_deps_licenses/zlib.txt
    - static_deps_licenses/zstd.txt
  summary: Create and extract conda packages of various formats
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - dbast
    - msarahan
