# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# C:\ci\containers\00000v9aeco\tmp\build\80754af9\rsync-recipes\certifi-2022.5.18.1-python_3.7-on-winbuilder, last modified Fri May 20 15:24:31 2022
# ------------------------------------------------

package:
  name: certifi
  version: 2022.5.18.1
source:
  - folder: certifi
    sha256: 9c5705e395cd70084351dd8ad5c41e65655e08ce46f2ec9cf6c2c08390f71eb7
    url: https://pypi.io/packages/source/c/certifi/certifi-2022.5.18.1.tar.gz
  - folder: pip_wheel
    sha256: 0f35d63b7245205f4060efe1982f5ea2196aa6e5b26c07669adcf800e2542026
    url: https://pypi.io/packages/py2.py3/p/pip/pip-20.2.3-py2.py3-none-any.whl
  - folder: setuptools_wheel
    sha256: 4dd5bb0a0a0cff77b46ca5dd3a84857ee48c83e8223886b556613c724994073f
    url: https://pypi.io/packages/py3/s/setuptools/setuptools-49.6.0-py3-none-any.whl
build:
  number: '0'
  string: py37haa95532_0
requirements:
  host:
    - ca-certificates 2022.4.26 haa95532_0
    - openssl 1.1.1o h2bbff1b_0
    - python 3.7.13 h6244533_0
    - sqlite 3.38.3 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - python >=3.7,<3.8.0a0
test:
  commands:
    - pip check || 1
  imports:
    - certifi
  requires:
    - pip
    - python >=3.7,<3.8.0a0
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_source_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  doc_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  home: https://github.com/certifi/python-certifi
  license: MPL-2.0
  license_family: Other
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
    - sigmavirus24
