# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# C:\ci\containers\0000219f4l3\tmp\build\80754af9\rsync-recipes\menuinst-1.4.18-python_3.9-on-winbuilder, last modified Wed Sep 15 13:57:58 2021
# ------------------------------------------------

package:
  name: menuinst
  version: 1.4.18
source:
  fn: menuinst-1.4.18.tar.gz
  sha256: f64adf261c8c0edfe5eaf929a57dce8c53b3bd043bc6ad41c85a708cd64a3363
  url: https://github.com/conda/menuinst/archive/1.4.18.tar.gz
build:
  entry_points:
    - menuinst = menuinst.main:main
  number: '0'
  script:
    - C:\\ci\\menuinst_1631733438520\\_h_env\\python.exe -m pip install . -vv
    - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"
  skip_compile_pyc:
    - cwp.py
  string: py39h59b6b97_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2021.7.5 haa95532_1
    - certifi 2021.5.30 py39haa95532_0
    - openssl 1.1.1l h2bbff1b_0
    - pip 21.2.4 py38haa95532_0
    - python 3.9.6 h6244533_1
    - setuptools 52.0.0 py39haa95532_0
    - sqlite 3.36.0 h2bbff1b_0
    - tzdata 2021a h5d7bf9c_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.0 pyhd3eb1b0_1
    - wincertstore 0.2 py39h2bbff1b_0
  run:
    - python >=3.9,<3.10.0a0
    - pywin32
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - menuinst --help
  imports:
    - menuinst
  requires:
    - pip
about:
  description: 'This application is used by Conda to create shortcuts on a wide variety
    of

    systems.

    '
  dev_url: https://github.com/conda/menuinst
  doc_url: https://github.com/conda/menuinst/wiki
  home: https://github.com/conda/menuinst
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - goanpeca
    - jakirkham
